/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
	eclipse
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()


	maven {
		url=uri("https://mvnrepository.com/artifact/org.jbpt/jbpt")
	}
	
	flatDir {
        dirs("../lib")
    }	
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")


    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")


	//jbpt
	implementation("org.jbpt:jbpt:0.3.1")
    implementation("org.jbpt:jbpt-petri:0.3.1")

    
    //uma
    //https://github.com/dfahland/uma    (v.1.3.0)
    //lib-externals: pnapi-java (compilar uma con ant build-src y copiar lib externals aqui)
    implementation(":umaBPDiff:1.0")
    implementation(":pnapi-java:")
    //implementation(":lpsolve55j:")
    //implementation(":antlr-runtime:3.2")
    
    //Simple pnml    
    implementation(":simple-pnml:1.0.0")                  

	// https://mvnrepository.com/artifact/commons-cli/commons-cli
	implementation("commons-cli:commons-cli:1.5.0")
	
	 // JAX-B dependencies for JDK 9+
	implementation("jakarta.xml.bind:jakarta.xml.bind-api:2.3.2")
	implementation("org.glassfish.jaxb:jaxb-runtime:2.3.2")
	
	
	implementation(":jdom:")
	implementation(":OpenXES-XStream:")	
	implementation(":OpenXES:")	
}

application {
    // Define the main class for the application.
    mainClass.set("unfold_01_jbpt.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
